version: '3'

services:
    nginx:
        image: nginx
        working_dir: /var/www/html
        ports:
            - "7050:80"
        links:
            - app
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/sites-available:/etc/nginx/conf.d/
        environment:       
            VIRTUAL_HOST: apidian.siit.cloud
            VIRTUAL_PORT: 7050
            LETSENCRYPT_HOST: apidian.siit.cloud
            LETSENCRYPT_EMAIL: soporte@siit.cloud
        networks:
            - default
   
    app:
        image: stenfrank/php:1.3
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        depends_on:
            - db
        links:
            - db
        networks:
            - default
    db:
        image: mariadb
        environment:
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        expose:
            - "3306"
        volumes:
            - mysqldata:/var/lib/mysql
        networks:
            - default

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db:db
        ports:
            - 7150:80
        environment:
            - VIRTUAL_HOST= ${VIRTUAL_HOST_DB}
            - VIRTUAL_PORT= ${VIRTUAL_PORT_DB}
            - LETSENCRYPT_HOST= ${VIRTUAL_HOST_DB}
            - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        networks:
            - default 

networks:
  default:
    external:
      name: ${NETWORK:-webproxy}


volumes:
    mysqldata:
        driver: "local"
