version: '3'

services:
    nginx:
        image: nginx
        working_dir: /var/www/html
        ports:
            - "8099:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/sites-available:/etc/nginx/conf.d/
        networks:
            - api_dian
    app:
        image: stenfrank/php:1.3
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        depends_on:
            - db
        networks:
            - api_dian
    db:
        image: mariadb
        environment:
            - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        expose:
            - "3306"
        volumes:
            - mysqldata:/var/lib/mysql
        networks:
            - api_dian

networks:
    api_dian:
        driver: "bridge"

volumes:
    mysqldata:
        driver: "local"
